import React, { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import "./Admin.css";
import "./ProductAdmin.css";

const API_URL = "http://localhost:5000/api";
const blankProduct = { name: "", nameTh: "", category: "clothing", price: "", stock: "0", badge: "ALL BLACK", style: "BLACK COTTON / BAGGY FIT", image: "", colors: ["#050505", "#242424", "#444444"] };

export default function Admin() {
  const navigate = useNavigate();
  const [user, setUser] = useState(null); const [products, setProducts] = useState([]); const [error, setError] = useState(""); const [form, setForm] = useState(blankProduct); const [editingId, setEditingId] = useState(null); const [saving, setSaving] = useState(false);
  const token = localStorage.getItem("token");
  const headers = { "Content-Type": "application/json", Authorization: `Bearer ${token}` };
  const loadProducts = () => fetch(`${API_URL}/products`).then((response) => response.json()).then((data) => setProducts(data.products || []));
  useEffect(() => { if (!token) { navigate("/login"); return; } fetch(`${API_URL}/auth/me`, { headers }).then(async (response) => ({ ok: response.ok, data: await response.json() })).then(({ ok, data }) => { if (!ok || data.user.role !== "admin") throw new Error("หน้านี้สำหรับผู้ดูแลระบบเท่านั้น"); setUser(data.user); return loadProducts(); }).catch((requestError) => setError(requestError.message)); }, []);
  const saveProduct = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const endpoint = editingId ? `${API_URL}/products/${editingId}` : `${API_URL}/products`; const response = await fetch(endpoint, { method: editingId ? "PUT" : "POST", headers, body: JSON.stringify({ ...form, price: Number(form.price), stock: Number(form.stock) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "บันทึกสินค้าไม่สำเร็จ"); setForm(blankProduct); setEditingId(null); await loadProducts(); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  const removeProduct = async (id) => { if (!window.confirm("ลบสินค้านี้ออกจากร้าน?")) return; const response = await fetch(`${API_URL}/products/${id}`, { method: "DELETE", headers }); if (!response.ok) { const data = await response.json(); setError(data.message || "ลบสินค้าไม่สำเร็จ"); return; } await loadProducts(); };
  const editProduct = (product) => { setForm({ ...product, price: String(product.price), stock: String(product.stock ?? 0) }); setEditingId(product.id); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const logout = () => { localStorage.removeItem("token"); localStorage.removeItem("user"); navigate("/"); };
  if (error && !user) return <main className="admin-page"><section className="admin-error"><p>ACCESS DENIED</p><h1>{error}</h1><Link to="/">กลับหน้าร้าน</Link></section></main>;
  return <main className="admin-page"><header className="admin-header"><Link className="brand" to="/">STREETWEAR <span>STORE</span></Link><div><span>{user?.fullName || "Loading..."}</span><button onClick={logout}>LOG OUT</button></div></header><section className="admin-content"><p className="section-kicker">ADMIN CONTROL ROOM</p><h1>STORE<br />MANAGER.</h1><div className="admin-stats"><article><b>{products.length}</b><span>สินค้าในคอลเลกชัน</span></article><article><b>{products.reduce((sum, product) => sum + Number(product.stock || 0), 0)}</b><span>สินค้าคงเหลือ</span></article><article><b>{products.filter((product) => product.category === "bags").length}</b><span>ไอเท็มกระเป๋า</span></article></div><form className="product-form" onSubmit={saveProduct}><h2>{editingId ? "EDIT PRODUCT" : "ADD PRODUCT"}</h2>{error && <p className="error-message">{error}</p>}<div><input placeholder="Product name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /><input placeholder="ชื่อสินค้าไทย" value={form.nameTh} onChange={(event) => setForm({ ...form, nameTh: event.target.value })} required /><select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}><option value="clothing">เสื้อผ้า</option><option value="bags">กระเป๋า</option></select><input type="number" min="0" placeholder="ราคา" value={form.price} onChange={(event) => setForm({ ...form, price: event.target.value })} required /><input type="number" min="0" placeholder="จำนวนสต็อก" value={form.stock} onChange={(event) => setForm({ ...form, stock: event.target.value })} required /><input placeholder="Image URL" value={form.image} onChange={(event) => setForm({ ...form, image: event.target.value })} required /><input placeholder="Style detail" value={form.style} onChange={(event) => setForm({ ...form, style: event.target.value })} /><input placeholder="Badge" value={form.badge} onChange={(event) => setForm({ ...form, badge: event.target.value })} /></div><button className="button" disabled={saving}>{saving ? "SAVING..." : editingId ? "SAVE CHANGES" : "ADD PRODUCT"}</button>{editingId && <button type="button" className="cancel-button" onClick={() => { setForm(blankProduct); setEditingId(null); }}>CANCEL</button>}</form><section className="admin-products"><div><h2>CATALOG</h2><p>เพิ่ม ลด แก้ไขราคา และจัดการสินค้าได้จากหน้านี้</p></div><div className="admin-list">{products.map((product) => <article key={product.id}><img src={product.image} alt="" /><div><b>{product.name}</b><span>{product.nameTh} · คงเหลือ {product.stock ?? 0} ชิ้น</span></div><strong>฿{product.price.toLocaleString()}</strong><button onClick={() => editProduct(product)}>EDIT</button><button className="delete-button" onClick={() => removeProduct(product.id)}>DELETE</button></article>)}</div></section></section></main>;
}
